import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignIn, SignUp,  SignInButton, SignOutButton, UserButton, useUser} from "@clerk/nextjs";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col text-white items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        wow
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}

        
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

      </main>
    </>
  );
};

export default Home;
